version: "3"
services:
  ui:
    build: ./ui/.
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
  api:
    build: ./api/.
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
  api2:
    build: ./api/.
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
