version: "3"
services:
  ui:
    build: ./ui/.
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
  api:
    build: ./api/.
    volumes:
      - "./api/node_modules:/app/node_modules"
  api2:
    build: ./api/.
    volumes:
      - "./api/node_modules:/app/node_modules"
