apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yuliangunawan/frontend
          ports:
            - name: frontend-port
              containerPort: 80
          volumeMounts:
            - name: config-nginx-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-nginx-volume
          configMap:
            name: nginx-configmap